export type CountryCode = {
  /** ISO 3166-1 alpha-2 */
  code: string;
  nom: string;
  indicatif: string;
  drapeau: string;
};

/**
 * Liste exhaustive des pays et territoires (ISO 3166-1) avec leur indicatif
 * téléphonique international, triée alphabétiquement sur le nom français.
 * Générée à partir du jeu de données world-countries (idd + translations.fra),
 * avec quelques corrections manuelles vérifiées pour les territoires dont le
 * préfixe partagé ne se déduit pas directement (Åland, Sainte-Hélène,
 * Sahara Occidental, République dominicaine, Porto Rico, Vatican).
 */
export const COUNTRY_CODES: CountryCode[] = [
  { code: "AF", nom: "Afghanistan", indicatif: "+93", drapeau: "🇦🇫" },
  { code: "ZA", nom: "Afrique du Sud", indicatif: "+27", drapeau: "🇿🇦" },
  { code: "AL", nom: "Albanie", indicatif: "+355", drapeau: "🇦🇱" },
  { code: "DZ", nom: "Algérie", indicatif: "+213", drapeau: "🇩🇿" },
  { code: "DE", nom: "Allemagne", indicatif: "+49", drapeau: "🇩🇪" },
  { code: "AD", nom: "Andorre", indicatif: "+376", drapeau: "🇦🇩" },
  { code: "AO", nom: "Angola", indicatif: "+244", drapeau: "🇦🇴" },
  { code: "AI", nom: "Anguilla", indicatif: "+1264", drapeau: "🇦🇮" },
  { code: "AG", nom: "Antigua-et-Barbuda", indicatif: "+1268", drapeau: "🇦🇬" },
  { code: "SA", nom: "Arabie Saoudite", indicatif: "+966", drapeau: "🇸🇦" },
  { code: "AR", nom: "Argentine", indicatif: "+54", drapeau: "🇦🇷" },
  { code: "AM", nom: "Arménie", indicatif: "+374", drapeau: "🇦🇲" },
  { code: "AW", nom: "Aruba", indicatif: "+297", drapeau: "🇦🇼" },
  { code: "AU", nom: "Australie", indicatif: "+61", drapeau: "🇦🇺" },
  { code: "AT", nom: "Autriche", indicatif: "+43", drapeau: "🇦🇹" },
  { code: "AZ", nom: "Azerbaïdjan", indicatif: "+994", drapeau: "🇦🇿" },
  { code: "BS", nom: "Bahamas", indicatif: "+1242", drapeau: "🇧🇸" },
  { code: "BH", nom: "Bahreïn", indicatif: "+973", drapeau: "🇧🇭" },
  { code: "BD", nom: "Bangladesh", indicatif: "+880", drapeau: "🇧🇩" },
  { code: "BB", nom: "Barbade", indicatif: "+1246", drapeau: "🇧🇧" },
  { code: "BE", nom: "Belgique", indicatif: "+32", drapeau: "🇧🇪" },
  { code: "BZ", nom: "Belize", indicatif: "+501", drapeau: "🇧🇿" },
  { code: "BJ", nom: "Bénin", indicatif: "+229", drapeau: "🇧🇯" },
  { code: "BM", nom: "Bermudes", indicatif: "+1441", drapeau: "🇧🇲" },
  { code: "BT", nom: "Bhoutan", indicatif: "+975", drapeau: "🇧🇹" },
  { code: "BY", nom: "Biélorussie", indicatif: "+375", drapeau: "🇧🇾" },
  { code: "MM", nom: "Birmanie", indicatif: "+95", drapeau: "🇲🇲" },
  { code: "BO", nom: "Bolivie", indicatif: "+591", drapeau: "🇧🇴" },
  { code: "BA", nom: "Bosnie-Herzégovine", indicatif: "+387", drapeau: "🇧🇦" },
  { code: "BW", nom: "Botswana", indicatif: "+267", drapeau: "🇧🇼" },
  { code: "BR", nom: "Brésil", indicatif: "+55", drapeau: "🇧🇷" },
  { code: "BN", nom: "Brunei", indicatif: "+673", drapeau: "🇧🇳" },
  { code: "BG", nom: "Bulgarie", indicatif: "+359", drapeau: "🇧🇬" },
  { code: "BF", nom: "Burkina Faso", indicatif: "+226", drapeau: "🇧🇫" },
  { code: "BI", nom: "Burundi", indicatif: "+257", drapeau: "🇧🇮" },
  { code: "KH", nom: "Cambodge", indicatif: "+855", drapeau: "🇰🇭" },
  { code: "CM", nom: "Cameroun", indicatif: "+237", drapeau: "🇨🇲" },
  { code: "CA", nom: "Canada", indicatif: "+1", drapeau: "🇨🇦" },
  { code: "CL", nom: "Chili", indicatif: "+56", drapeau: "🇨🇱" },
  { code: "CN", nom: "Chine", indicatif: "+86", drapeau: "🇨🇳" },
  { code: "CY", nom: "Chypre", indicatif: "+357", drapeau: "🇨🇾" },
  { code: "VA", nom: "Cité du Vatican", indicatif: "+379", drapeau: "🇻🇦" },
  { code: "CO", nom: "Colombie", indicatif: "+57", drapeau: "🇨🇴" },
  { code: "KM", nom: "Comores", indicatif: "+269", drapeau: "🇰🇲" },
  { code: "CG", nom: "Congo", indicatif: "+242", drapeau: "🇨🇬" },
  { code: "CD", nom: "Congo (Rép. dém.)", indicatif: "+243", drapeau: "🇨🇩" },
  { code: "KP", nom: "Corée du Nord", indicatif: "+850", drapeau: "🇰🇵" },
  { code: "KR", nom: "Corée du Sud", indicatif: "+82", drapeau: "🇰🇷" },
  { code: "CR", nom: "Costa Rica", indicatif: "+506", drapeau: "🇨🇷" },
  { code: "CI", nom: "Côte d'Ivoire", indicatif: "+225", drapeau: "🇨🇮" },
  { code: "HR", nom: "Croatie", indicatif: "+385", drapeau: "🇭🇷" },
  { code: "CU", nom: "Cuba", indicatif: "+53", drapeau: "🇨🇺" },
  { code: "CW", nom: "Curaçao", indicatif: "+599", drapeau: "🇨🇼" },
  { code: "DK", nom: "Danemark", indicatif: "+45", drapeau: "🇩🇰" },
  { code: "DJ", nom: "Djibouti", indicatif: "+253", drapeau: "🇩🇯" },
  { code: "DM", nom: "Dominique", indicatif: "+1767", drapeau: "🇩🇲" },
  { code: "EG", nom: "Égypte", indicatif: "+20", drapeau: "🇪🇬" },
  { code: "AE", nom: "Émirats arabes unis", indicatif: "+971", drapeau: "🇦🇪" },
  { code: "EC", nom: "Équateur", indicatif: "+593", drapeau: "🇪🇨" },
  { code: "ER", nom: "Érythrée", indicatif: "+291", drapeau: "🇪🇷" },
  { code: "ES", nom: "Espagne", indicatif: "+34", drapeau: "🇪🇸" },
  { code: "EE", nom: "Estonie", indicatif: "+372", drapeau: "🇪🇪" },
  { code: "US", nom: "États-Unis", indicatif: "+1", drapeau: "🇺🇸" },
  { code: "ET", nom: "Éthiopie", indicatif: "+251", drapeau: "🇪🇹" },
  { code: "FJ", nom: "Fidji", indicatif: "+679", drapeau: "🇫🇯" },
  { code: "FI", nom: "Finlande", indicatif: "+358", drapeau: "🇫🇮" },
  { code: "FR", nom: "France", indicatif: "+33", drapeau: "🇫🇷" },
  { code: "GA", nom: "Gabon", indicatif: "+241", drapeau: "🇬🇦" },
  { code: "GM", nom: "Gambie", indicatif: "+220", drapeau: "🇬🇲" },
  { code: "GE", nom: "Géorgie", indicatif: "+995", drapeau: "🇬🇪" },
  {
    code: "GS",
    nom: "Géorgie du Sud-et-les Îles Sandwich du Sud",
    indicatif: "+500",
    drapeau: "🇬🇸",
  },
  { code: "GH", nom: "Ghana", indicatif: "+233", drapeau: "🇬🇭" },
  { code: "GI", nom: "Gibraltar", indicatif: "+350", drapeau: "🇬🇮" },
  { code: "GR", nom: "Grèce", indicatif: "+30", drapeau: "🇬🇷" },
  { code: "GD", nom: "Grenade", indicatif: "+1473", drapeau: "🇬🇩" },
  { code: "GL", nom: "Groenland", indicatif: "+299", drapeau: "🇬🇱" },
  { code: "GP", nom: "Guadeloupe", indicatif: "+590", drapeau: "🇬🇵" },
  { code: "GU", nom: "Guam", indicatif: "+1671", drapeau: "🇬🇺" },
  { code: "GT", nom: "Guatemala", indicatif: "+502", drapeau: "🇬🇹" },
  { code: "GG", nom: "Guernesey", indicatif: "+44", drapeau: "🇬🇬" },
  { code: "GN", nom: "Guinée", indicatif: "+224", drapeau: "🇬🇳" },
  { code: "GQ", nom: "Guinée équatoriale", indicatif: "+240", drapeau: "🇬🇶" },
  { code: "GW", nom: "Guinée-Bissau", indicatif: "+245", drapeau: "🇬🇼" },
  { code: "GY", nom: "Guyana", indicatif: "+592", drapeau: "🇬🇾" },
  { code: "GF", nom: "Guyane", indicatif: "+594", drapeau: "🇬🇫" },
  { code: "HT", nom: "Haïti", indicatif: "+509", drapeau: "🇭🇹" },
  { code: "HN", nom: "Honduras", indicatif: "+504", drapeau: "🇭🇳" },
  { code: "HK", nom: "Hong Kong", indicatif: "+852", drapeau: "🇭🇰" },
  { code: "HU", nom: "Hongrie", indicatif: "+36", drapeau: "🇭🇺" },
  { code: "BV", nom: "Île Bouvet", indicatif: "+47", drapeau: "🇧🇻" },
  { code: "CX", nom: "Île Christmas", indicatif: "+61", drapeau: "🇨🇽" },
  { code: "IM", nom: "Île de Man", indicatif: "+44", drapeau: "🇮🇲" },
  { code: "MU", nom: "Île Maurice", indicatif: "+230", drapeau: "🇲🇺" },
  { code: "NF", nom: "Île Norfolk", indicatif: "+672", drapeau: "🇳🇫" },
  { code: "AX", nom: "Îles Åland", indicatif: "+358", drapeau: "🇦🇽" },
  { code: "KY", nom: "Îles Caïmans", indicatif: "+1345", drapeau: "🇰🇾" },
  { code: "CC", nom: "Îles Cocos", indicatif: "+61", drapeau: "🇨🇨" },
  { code: "CK", nom: "Îles Cook", indicatif: "+682", drapeau: "🇨🇰" },
  { code: "CV", nom: "Îles du Cap-Vert", indicatif: "+238", drapeau: "🇨🇻" },
  { code: "FO", nom: "Îles Féroé", indicatif: "+298", drapeau: "🇫🇴" },
  { code: "FK", nom: "Îles Malouines", indicatif: "+500", drapeau: "🇫🇰" },
  { code: "MP", nom: "Îles Mariannes du Nord", indicatif: "+1670", drapeau: "🇲🇵" },
  { code: "MH", nom: "Îles Marshall", indicatif: "+692", drapeau: "🇲🇭" },
  { code: "UM", nom: "Îles mineures éloignées des États-Unis", indicatif: "+268", drapeau: "🇺🇲" },
  { code: "PN", nom: "Îles Pitcairn", indicatif: "+64", drapeau: "🇵🇳" },
  { code: "SB", nom: "Îles Salomon", indicatif: "+677", drapeau: "🇸🇧" },
  { code: "TC", nom: "Îles Turques-et-Caïques", indicatif: "+1649", drapeau: "🇹🇨" },
  { code: "VG", nom: "Îles Vierges britanniques", indicatif: "+1284", drapeau: "🇻🇬" },
  { code: "VI", nom: "Îles Vierges des États-Unis", indicatif: "+1340", drapeau: "🇻🇮" },
  { code: "IN", nom: "Inde", indicatif: "+91", drapeau: "🇮🇳" },
  { code: "ID", nom: "Indonésie", indicatif: "+62", drapeau: "🇮🇩" },
  { code: "IQ", nom: "Irak", indicatif: "+964", drapeau: "🇮🇶" },
  { code: "IR", nom: "Iran", indicatif: "+98", drapeau: "🇮🇷" },
  { code: "IE", nom: "Irlande", indicatif: "+353", drapeau: "🇮🇪" },
  { code: "IS", nom: "Islande", indicatif: "+354", drapeau: "🇮🇸" },
  { code: "IL", nom: "Israël", indicatif: "+972", drapeau: "🇮🇱" },
  { code: "IT", nom: "Italie", indicatif: "+39", drapeau: "🇮🇹" },
  { code: "JM", nom: "Jamaïque", indicatif: "+1876", drapeau: "🇯🇲" },
  { code: "JP", nom: "Japon", indicatif: "+81", drapeau: "🇯🇵" },
  { code: "JE", nom: "Jersey", indicatif: "+44", drapeau: "🇯🇪" },
  { code: "JO", nom: "Jordanie", indicatif: "+962", drapeau: "🇯🇴" },
  { code: "KZ", nom: "Kazakhstan", indicatif: "+7", drapeau: "🇰🇿" },
  { code: "KE", nom: "Kenya", indicatif: "+254", drapeau: "🇰🇪" },
  { code: "KG", nom: "Kirghizistan", indicatif: "+996", drapeau: "🇰🇬" },
  { code: "KI", nom: "Kiribati", indicatif: "+686", drapeau: "🇰🇮" },
  { code: "XK", nom: "Kosovo", indicatif: "+383", drapeau: "🇽🇰" },
  { code: "KW", nom: "Koweït", indicatif: "+965", drapeau: "🇰🇼" },
  { code: "LA", nom: "Laos", indicatif: "+856", drapeau: "🇱🇦" },
  { code: "LS", nom: "Lesotho", indicatif: "+266", drapeau: "🇱🇸" },
  { code: "LV", nom: "Lettonie", indicatif: "+371", drapeau: "🇱🇻" },
  { code: "LB", nom: "Liban", indicatif: "+961", drapeau: "🇱🇧" },
  { code: "LR", nom: "Liberia", indicatif: "+231", drapeau: "🇱🇷" },
  { code: "LY", nom: "Libye", indicatif: "+218", drapeau: "🇱🇾" },
  { code: "LI", nom: "Liechtenstein", indicatif: "+423", drapeau: "🇱🇮" },
  { code: "LT", nom: "Lituanie", indicatif: "+370", drapeau: "🇱🇹" },
  { code: "LU", nom: "Luxembourg", indicatif: "+352", drapeau: "🇱🇺" },
  { code: "MO", nom: "Macao", indicatif: "+853", drapeau: "🇲🇴" },
  { code: "MK", nom: "Macédoine du Nord", indicatif: "+389", drapeau: "🇲🇰" },
  { code: "MG", nom: "Madagascar", indicatif: "+261", drapeau: "🇲🇬" },
  { code: "MY", nom: "Malaisie", indicatif: "+60", drapeau: "🇲🇾" },
  { code: "MW", nom: "Malawi", indicatif: "+265", drapeau: "🇲🇼" },
  { code: "MV", nom: "Maldives", indicatif: "+960", drapeau: "🇲🇻" },
  { code: "ML", nom: "Mali", indicatif: "+223", drapeau: "🇲🇱" },
  { code: "MT", nom: "Malte", indicatif: "+356", drapeau: "🇲🇹" },
  { code: "MA", nom: "Maroc", indicatif: "+212", drapeau: "🇲🇦" },
  { code: "MQ", nom: "Martinique", indicatif: "+596", drapeau: "🇲🇶" },
  { code: "MR", nom: "Mauritanie", indicatif: "+222", drapeau: "🇲🇷" },
  { code: "YT", nom: "Mayotte", indicatif: "+262", drapeau: "🇾🇹" },
  { code: "MX", nom: "Mexique", indicatif: "+52", drapeau: "🇲🇽" },
  { code: "FM", nom: "Micronésie", indicatif: "+691", drapeau: "🇫🇲" },
  { code: "MD", nom: "Moldavie", indicatif: "+373", drapeau: "🇲🇩" },
  { code: "MC", nom: "Monaco", indicatif: "+377", drapeau: "🇲🇨" },
  { code: "MN", nom: "Mongolie", indicatif: "+976", drapeau: "🇲🇳" },
  { code: "ME", nom: "Monténégro", indicatif: "+382", drapeau: "🇲🇪" },
  { code: "MS", nom: "Montserrat", indicatif: "+1664", drapeau: "🇲🇸" },
  { code: "MZ", nom: "Mozambique", indicatif: "+258", drapeau: "🇲🇿" },
  { code: "NA", nom: "Namibie", indicatif: "+264", drapeau: "🇳🇦" },
  { code: "NR", nom: "Nauru", indicatif: "+674", drapeau: "🇳🇷" },
  { code: "NP", nom: "Népal", indicatif: "+977", drapeau: "🇳🇵" },
  { code: "NI", nom: "Nicaragua", indicatif: "+505", drapeau: "🇳🇮" },
  { code: "NE", nom: "Niger", indicatif: "+227", drapeau: "🇳🇪" },
  { code: "NG", nom: "Nigéria", indicatif: "+234", drapeau: "🇳🇬" },
  { code: "NU", nom: "Niue", indicatif: "+683", drapeau: "🇳🇺" },
  { code: "NO", nom: "Norvège", indicatif: "+47", drapeau: "🇳🇴" },
  { code: "NC", nom: "Nouvelle-Calédonie", indicatif: "+687", drapeau: "🇳🇨" },
  { code: "NZ", nom: "Nouvelle-Zélande", indicatif: "+64", drapeau: "🇳🇿" },
  { code: "OM", nom: "Oman", indicatif: "+968", drapeau: "🇴🇲" },
  { code: "UG", nom: "Ouganda", indicatif: "+256", drapeau: "🇺🇬" },
  { code: "UZ", nom: "Ouzbékistan", indicatif: "+998", drapeau: "🇺🇿" },
  { code: "PK", nom: "Pakistan", indicatif: "+92", drapeau: "🇵🇰" },
  { code: "PW", nom: "Palaos (Palau)", indicatif: "+680", drapeau: "🇵🇼" },
  { code: "PS", nom: "Palestine", indicatif: "+970", drapeau: "🇵🇸" },
  { code: "PA", nom: "Panama", indicatif: "+507", drapeau: "🇵🇦" },
  { code: "PG", nom: "Papouasie-Nouvelle-Guinée", indicatif: "+675", drapeau: "🇵🇬" },
  { code: "PY", nom: "Paraguay", indicatif: "+595", drapeau: "🇵🇾" },
  { code: "NL", nom: "Pays-Bas", indicatif: "+31", drapeau: "🇳🇱" },
  { code: "BQ", nom: "Pays-Bas caribéens", indicatif: "+599", drapeau: "" },
  { code: "PE", nom: "Pérou", indicatif: "+51", drapeau: "🇵🇪" },
  { code: "PH", nom: "Philippines", indicatif: "+63", drapeau: "🇵🇭" },
  { code: "PL", nom: "Pologne", indicatif: "+48", drapeau: "🇵🇱" },
  { code: "PF", nom: "Polynésie française", indicatif: "+689", drapeau: "🇵🇫" },
  { code: "PR", nom: "Porto Rico", indicatif: "+1787", drapeau: "🇵🇷" },
  { code: "PT", nom: "Portugal", indicatif: "+351", drapeau: "🇵🇹" },
  { code: "QA", nom: "Qatar", indicatif: "+974", drapeau: "🇶🇦" },
  { code: "CF", nom: "République centrafricaine", indicatif: "+236", drapeau: "🇨🇫" },
  { code: "DO", nom: "République dominicaine", indicatif: "+1809", drapeau: "🇩🇴" },
  { code: "RE", nom: "Réunion", indicatif: "+262", drapeau: "🇷🇪" },
  { code: "RO", nom: "Roumanie", indicatif: "+40", drapeau: "🇷🇴" },
  { code: "GB", nom: "Royaume-Uni", indicatif: "+44", drapeau: "🇬🇧" },
  { code: "RU", nom: "Russie", indicatif: "+7", drapeau: "🇷🇺" },
  { code: "RW", nom: "Rwanda", indicatif: "+250", drapeau: "🇷🇼" },
  { code: "EH", nom: "Sahara Occidental", indicatif: "+212", drapeau: "🇪🇭" },
  { code: "BL", nom: "Saint-Barthélemy", indicatif: "+590", drapeau: "🇧🇱" },
  { code: "KN", nom: "Saint-Christophe-et-Niévès", indicatif: "+1869", drapeau: "🇰🇳" },
  { code: "SM", nom: "Saint-Marin", indicatif: "+378", drapeau: "🇸🇲" },
  { code: "MF", nom: "Saint-Martin", indicatif: "+590", drapeau: "🇲🇫" },
  { code: "SX", nom: "Saint-Martin", indicatif: "+1721", drapeau: "🇸🇽" },
  { code: "PM", nom: "Saint-Pierre-et-Miquelon", indicatif: "+508", drapeau: "🇵🇲" },
  { code: "VC", nom: "Saint-Vincent-et-les-Grenadines", indicatif: "+1784", drapeau: "🇻🇨" },
  {
    code: "SH",
    nom: "Sainte-Hélène, Ascension et Tristan da Cunha",
    indicatif: "+290",
    drapeau: "🇸🇭",
  },
  { code: "LC", nom: "Sainte-Lucie", indicatif: "+1758", drapeau: "🇱🇨" },
  { code: "SV", nom: "Salvador", indicatif: "+503", drapeau: "🇸🇻" },
  { code: "WS", nom: "Samoa", indicatif: "+685", drapeau: "🇼🇸" },
  { code: "AS", nom: "Samoa américaines", indicatif: "+1684", drapeau: "🇦🇸" },
  { code: "ST", nom: "São Tomé et Príncipe", indicatif: "+239", drapeau: "🇸🇹" },
  { code: "SN", nom: "Sénégal", indicatif: "+221", drapeau: "🇸🇳" },
  { code: "RS", nom: "Serbie", indicatif: "+381", drapeau: "🇷🇸" },
  { code: "SC", nom: "Seychelles", indicatif: "+248", drapeau: "🇸🇨" },
  { code: "SL", nom: "Sierra Leone", indicatif: "+232", drapeau: "🇸🇱" },
  { code: "SG", nom: "Singapour", indicatif: "+65", drapeau: "🇸🇬" },
  { code: "SK", nom: "Slovaquie", indicatif: "+421", drapeau: "🇸🇰" },
  { code: "SI", nom: "Slovénie", indicatif: "+386", drapeau: "🇸🇮" },
  { code: "SO", nom: "Somalie", indicatif: "+252", drapeau: "🇸🇴" },
  { code: "SD", nom: "Soudan", indicatif: "+249", drapeau: "🇸🇩" },
  { code: "SS", nom: "Soudan du Sud", indicatif: "+211", drapeau: "🇸🇸" },
  { code: "LK", nom: "Sri Lanka", indicatif: "+94", drapeau: "🇱🇰" },
  { code: "SE", nom: "Suède", indicatif: "+46", drapeau: "🇸🇪" },
  { code: "CH", nom: "Suisse", indicatif: "+41", drapeau: "🇨🇭" },
  { code: "SR", nom: "Surinam", indicatif: "+597", drapeau: "🇸🇷" },
  { code: "SJ", nom: "Svalbard et Jan Mayen", indicatif: "+4779", drapeau: "🇸🇯" },
  { code: "SZ", nom: "Swaziland", indicatif: "+268", drapeau: "🇸🇿" },
  { code: "SY", nom: "Syrie", indicatif: "+963", drapeau: "🇸🇾" },
  { code: "TJ", nom: "Tadjikistan", indicatif: "+992", drapeau: "🇹🇯" },
  { code: "TW", nom: "Taïwan", indicatif: "+886", drapeau: "🇹🇼" },
  { code: "TZ", nom: "Tanzanie", indicatif: "+255", drapeau: "🇹🇿" },
  { code: "TD", nom: "Tchad", indicatif: "+235", drapeau: "🇹🇩" },
  { code: "CZ", nom: "Tchéquie", indicatif: "+420", drapeau: "🇨🇿" },
  {
    code: "TF",
    nom: "Terres australes et antarctiques françaises",
    indicatif: "+262",
    drapeau: "🇹🇫",
  },
  { code: "IO", nom: "Territoire britannique de l'océan Indien", indicatif: "+246", drapeau: "🇮🇴" },
  { code: "TH", nom: "Thaïlande", indicatif: "+66", drapeau: "🇹🇭" },
  { code: "TL", nom: "Timor oriental", indicatif: "+670", drapeau: "🇹🇱" },
  { code: "TG", nom: "Togo", indicatif: "+228", drapeau: "🇹🇬" },
  { code: "TK", nom: "Tokelau", indicatif: "+690", drapeau: "🇹🇰" },
  { code: "TO", nom: "Tonga", indicatif: "+676", drapeau: "🇹🇴" },
  { code: "TT", nom: "Trinité-et-Tobago", indicatif: "+1868", drapeau: "🇹🇹" },
  { code: "TN", nom: "Tunisie", indicatif: "+216", drapeau: "🇹🇳" },
  { code: "TM", nom: "Turkménistan", indicatif: "+993", drapeau: "🇹🇲" },
  { code: "TR", nom: "Turquie", indicatif: "+90", drapeau: "🇹🇷" },
  { code: "TV", nom: "Tuvalu", indicatif: "+688", drapeau: "🇹🇻" },
  { code: "UA", nom: "Ukraine", indicatif: "+380", drapeau: "🇺🇦" },
  { code: "UY", nom: "Uruguay", indicatif: "+598", drapeau: "🇺🇾" },
  { code: "VU", nom: "Vanuatu", indicatif: "+678", drapeau: "🇻🇺" },
  { code: "VE", nom: "Venezuela", indicatif: "+58", drapeau: "🇻🇪" },
  { code: "VN", nom: "Viêt Nam", indicatif: "+84", drapeau: "🇻🇳" },
  { code: "WF", nom: "Wallis-et-Futuna", indicatif: "+681", drapeau: "🇼🇫" },
  { code: "YE", nom: "Yémen", indicatif: "+967", drapeau: "🇾🇪" },
  { code: "ZM", nom: "Zambie", indicatif: "+260", drapeau: "🇿🇲" },
  { code: "ZW", nom: "Zimbabwe", indicatif: "+263", drapeau: "🇿🇼" },
];

export const DEFAULT_COUNTRY_CODE = "+33";
